---
# Role: common
#common_upgrade_packages: true
#common_reboot_handler_enabled: true
#common_timezone: UTC
#common_usb_ssd_enabled: false
#common_usb_ssd_device_id: ""
common_rpi_overclock: true
#common_rpi_poe_hat: false
common_log2ram_version: 1.6.0
common_log2ram_size: 256M

# Role: kubernetes
kubernetes_kubectl_version: 1.19.3-00
kubernetes_kubelet_version: 1.19.3-00
kubernetes_kubeadm_version: 1.19.3-00

# Role: cri
cri_plugin: docker

# Role: openebs
openebs_enabled: true
