---
- name: check os_family support
  assert:
    that:
      - ansible_os_family | lower in openebs_supported_os_families
    fail_msg:
      - "os_family '{{ ansible_os_family }}' is not supported at this time"

- name: 'validate variable : openebs_enabled'
  assert:
    that:
      - openebs_enabled | type_debug == 'bool'
    fail_msg:
      - "Variable 'openebs_enabled' should be of type 'bool'"
      - 'Type is: {{ openebs_enabled | type_debug }}'
      - "Value is: {{ openebs_enabled | default('undefined') }}"
