---
- name: 'APT Installation'
  when: ansible_os_family|lower == 'debian'
  block:
  - name: 'containerd | ensure docker.io apt repository public key is installed'
    ansible.builtin.apt_key:
      url: '{{ containerd_repo_gpgkey }}'
  - name: 'containerd | ensure docker.io apt repository is enabled'
    ansible.builtin.apt_repository:
      repo: 'deb {{ containerd_repo_base_url }} {{ ansible_lsb.codename }} stable'
      state: 'present'
  # this is to prevent apt upgrade from breaking kubernetes
  - name: 'containerd | pin package version to prevent os upgrade clubbing'
    ansible.builtin.template:
      src: 'apt-preferences.d/containerd.j2'
      dest: '/etc/apt/preferences.d/containerd'
      owner: 'root'
      mode: 0644
  - name: 'containerd | install package from apt repository'
    ansible.builtin.apt:
      name:
        - '{{ containerd_package_name[containerd_version | string] }}'
      state: 'present'
      update_cache: true
      cache_valid_time: 3600

- name: 'containerd | ensure "{{ containerd_config_dir }}" config directory'
  ansible.builtin.file:
    path: '{{ containerd_config_dir }}'
    state: 'directory'
    mode: 0755
    owner: 'root'
    group: 'root'

# Hacky - need to create a better way to handle existing files
- name: 'containerd | move aside any existing config.toml'
  ansible.builtin.file:
    path: '{{ containerd_config_dir }}/config.toml'
    state: 'absent'

- name: 'containerd | ensure default configuration'
  ansible.builtin.shell: |
    containerd config default > {{ containerd_config_dir }}/config.toml
  args:
    creates: '{{ containerd_config_dir }}/config.toml'
  notify: restart cri

- include_tasks: 'crictl.yml'
